package kristenstuffs.uselessores.world;

import kristenstuffs.uselessores.init.BlockList;
import net.minecraft.block.Blocks;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.biome.Biomes;
import net.minecraft.world.gen.GenerationStage.Decoration;
import net.minecraft.world.gen.feature.Feature;
import net.minecraft.world.gen.feature.OreFeatureConfig;
import net.minecraft.world.gen.feature.OreFeatureConfig.FillerBlockType;
import net.minecraft.world.gen.feature.ReplaceBlockConfig;
import net.minecraft.world.gen.placement.CountRangeConfig;
import net.minecraft.world.gen.placement.Placement;
import net.minecraftforge.registries.ForgeRegistries;

public class OreGeneration

{
	
	public static void	setupOreGeneration()
	
	
	{
		for(Biome biome : ForgeRegistries.BIOMES)

		{
		
			
			// Spawns Per Chunk, Minimum Height, Maximum Height Base, and Maximum Height
			// Overworld
			// Ores
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.copper_ore.getDefaultState(), 35), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.ore_ore.getDefaultState(), 16), Placement.COUNT_RANGE, new CountRangeConfig(10, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.illusion_ore.getDefaultState(), 8), Placement.COUNT_RANGE, new CountRangeConfig(8, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.missing_texture_ore.getDefaultState(), 8), Placement.COUNT_RANGE, new CountRangeConfig(10, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.loot_box_ore.getDefaultState(), 12), Placement.COUNT_RANGE, new CountRangeConfig(12, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.copper_loot_box_ore.getDefaultState(), 8), Placement.COUNT_RANGE, new CountRangeConfig(8, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.pink_loot_box_ore.getDefaultState(), 8), Placement.COUNT_RANGE, new CountRangeConfig(8, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.four_ninety_nine_loot_box_ore.getDefaultState(), 10), Placement.COUNT_RANGE, new CountRangeConfig(10, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.nine_ninety_nine_loot_box_ore.getDefaultState(), 8), Placement.COUNT_RANGE, new CountRangeConfig(8, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.fourteen_ninety_nine_loot_box_ore.getDefaultState(), 6), Placement.COUNT_RANGE, new CountRangeConfig(6, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.nineteen_ninety_nine_loot_box_ore.getDefaultState(), 4), Placement.COUNT_RANGE, new CountRangeConfig(4, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.tyn_ore.getDefaultState(), 10), Placement.COUNT_RANGE, new CountRangeConfig(10, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.pest_ore.getDefaultState(), 35), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.incomplet_ore.getDefaultState(), 8), Placement.COUNT_RANGE, new CountRangeConfig(8, 1, 0, 48)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.chaos_ore.getDefaultState(), 8), Placement.COUNT_RANGE, new CountRangeConfig(8, 1, 0, 16)));		
			
			
			// Not Ores
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.rock.getDefaultState(), 35), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.diorite2.getDefaultState(), 35), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 255)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NATURAL_STONE, BlockList.marple.getDefaultState(), 35), Placement.COUNT_RANGE, new CountRangeConfig(10, 1, 0, 255)));
			
			// Overworld all Grass Block Spawning Biomes
			// Litter Ore
			Biomes.PLAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SUNFLOWER_PLAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));			
			Biomes.FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.FLOWER_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));		
			Biomes.BIRCH_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.BIRCH_FOREST_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.TALL_BIRCH_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.TALL_BIRCH_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.DARK_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.DARK_FOREST_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SWAMP.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SWAMP_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SAVANNA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SAVANNA_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SHATTERED_SAVANNA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SHATTERED_SAVANNA_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.MODIFIED_WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.GRAVELLY_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.WOODED_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.MODIFIED_GRAVELLY_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.TAIGA_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.GIANT_SPRUCE_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.GIANT_SPRUCE_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.GIANT_TREE_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.GIANT_TREE_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SNOWY_TUNDRA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SNOWY_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SNOWY_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SNOWY_TAIGA_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.RIVER.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.DEEP_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.COLD_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.DEEP_COLD_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.LUKEWARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.DEEP_LUKEWARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.WARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.litter_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
	
			// Water Ore
			Biomes.PLAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SUNFLOWER_PLAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));			
			Biomes.FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.FLOWER_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));		
			Biomes.BIRCH_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.BIRCH_FOREST_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TALL_BIRCH_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TALL_BIRCH_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DARK_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DARK_FOREST_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SWAMP.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SWAMP_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DESERT_LAKES.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));			
			Biomes.SAVANNA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SAVANNA_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SHATTERED_SAVANNA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SHATTERED_SAVANNA_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.BADLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.MODIFIED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.MODIFIED_WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.ERODED_BADLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GRAVELLY_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.WOODED_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.MODIFIED_GRAVELLY_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TAIGA_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GIANT_SPRUCE_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GIANT_SPRUCE_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GIANT_TREE_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GIANT_TREE_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SNOWY_TUNDRA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SNOWY_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SNOWY_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SNOWY_TAIGA_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.RIVER.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DEEP_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.COLD_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DEEP_COLD_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.LUKEWARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DEEP_LUKEWARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
		    Biomes.WARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));					
		    Biomes.FROZEN_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));					
		    Biomes.DEEP_FROZEN_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.WATER.getDefaultState(), BlockList.water_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));					
			
			// Not Ore	
		    // Sandy Sand
			Biomes.PLAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SUNFLOWER_PLAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));			
			Biomes.FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.FLOWER_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));		
			Biomes.BIRCH_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.BIRCH_FOREST_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TALL_BIRCH_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TALL_BIRCH_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DARK_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DARK_FOREST_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SWAMP.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SWAMP_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DESERT_LAKES.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));			
			Biomes.SAVANNA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SAVANNA_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SHATTERED_SAVANNA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SHATTERED_SAVANNA_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.BADLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.MODIFIED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.MODIFIED_WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.ERODED_BADLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GRAVELLY_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.WOODED_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.MODIFIED_GRAVELLY_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TAIGA_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GIANT_SPRUCE_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GIANT_SPRUCE_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GIANT_TREE_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GIANT_TREE_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SNOWY_TUNDRA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SNOWY_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SNOWY_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SNOWY_TAIGA_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.RIVER.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DEEP_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.COLD_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DEEP_COLD_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.LUKEWARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DEEP_LUKEWARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
		    Biomes.WARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));		    
		    Biomes.FROZEN_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));					
		    Biomes.DEEP_FROZEN_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));					
		 
		    // Quick Sand
			Biomes.PLAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SUNFLOWER_PLAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));			
			Biomes.FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.FLOWER_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));		
			Biomes.BIRCH_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.BIRCH_FOREST_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TALL_BIRCH_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TALL_BIRCH_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DARK_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DARK_FOREST_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SWAMP.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SWAMP_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DESERT_LAKES.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));			
			Biomes.SAVANNA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SAVANNA_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SHATTERED_SAVANNA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SHATTERED_SAVANNA_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.BADLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.MODIFIED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.MODIFIED_WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.ERODED_BADLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GRAVELLY_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.WOODED_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.MODIFIED_GRAVELLY_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.TAIGA_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GIANT_SPRUCE_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GIANT_SPRUCE_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GIANT_TREE_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.GIANT_TREE_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SNOWY_TUNDRA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SNOWY_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SNOWY_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.SNOWY_TAIGA_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.RIVER.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DEEP_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.COLD_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DEEP_COLD_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.LUKEWARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
			Biomes.DEEP_LUKEWARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
		    Biomes.WARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));		    
		    Biomes.FROZEN_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));					
		    Biomes.DEEP_FROZEN_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.SAND.getDefaultState(), BlockList.quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));	
		    
		    // Red Sandy Sand
		    Biomes.BADLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.RED_SAND.getDefaultState(), BlockList.red_sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));	
		    Biomes.BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.RED_SAND.getDefaultState(), BlockList.red_sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));	
		    Biomes.ERODED_BADLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.RED_SAND.getDefaultState(), BlockList.red_sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));	
		    Biomes.MODIFIED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.RED_SAND.getDefaultState(), BlockList.red_sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));	
		    Biomes.MODIFIED_WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.RED_SAND.getDefaultState(), BlockList.red_sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));	
		    Biomes.WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.RED_SAND.getDefaultState(), BlockList.red_sandy_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));	
		    
	
		    // Red Quick Sand
		    Biomes.BADLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.RED_SAND.getDefaultState(), BlockList.red_quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));	
		    Biomes.BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.RED_SAND.getDefaultState(), BlockList.red_quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));	
		    Biomes.ERODED_BADLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.RED_SAND.getDefaultState(), BlockList.red_quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));	
		    Biomes.MODIFIED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.RED_SAND.getDefaultState(), BlockList.red_quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));	
		    Biomes.MODIFIED_WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.RED_SAND.getDefaultState(), BlockList.red_quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));	
		    Biomes.WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.RED_SAND.getDefaultState(), BlockList.red_quick_sand.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));	
		    
			// Black Ice
			Biomes.PLAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SUNFLOWER_PLAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));			
			Biomes.FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.FLOWER_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));		
			Biomes.BIRCH_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.BIRCH_FOREST_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.TALL_BIRCH_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.TALL_BIRCH_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.DARK_FOREST.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.DARK_FOREST_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SWAMP.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SWAMP_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SAVANNA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SAVANNA_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SHATTERED_SAVANNA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SHATTERED_SAVANNA_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.MODIFIED_WOODED_BADLANDS_PLATEAU.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.GRAVELLY_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.WOODED_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.MODIFIED_GRAVELLY_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.TAIGA_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.GIANT_SPRUCE_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.GIANT_SPRUCE_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.GIANT_TREE_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.GIANT_TREE_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SNOWY_TUNDRA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SNOWY_TAIGA.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SNOWY_TAIGA_HILLS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.SNOWY_TAIGA_MOUNTAINS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.RIVER.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.DEEP_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.COLD_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.DEEP_COLD_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.LUKEWARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.DEEP_LUKEWARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
			Biomes.WARM_OCEAN.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.GRASS_BLOCK.getDefaultState(), BlockList.black_ice.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 48, 0, 128)));
		
		    
			// Nether
			// Ores
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NETHERRACK, BlockList.nether_copper_ore.getDefaultState(), 35), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 128)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NETHERRACK, BlockList.wither_ore.getDefaultState(), 25), Placement.COUNT_RANGE, new CountRangeConfig(15, 23, 0, 33)));
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NETHERRACK, BlockList.ende_purple_doritos_ore.getDefaultState(), 20), Placement.COUNT_RANGE, new CountRangeConfig(10, 1, 0, 128)));
		
			// Not Ores
			biome.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(FillerBlockType.NETHERRACK, BlockList.rock.getDefaultState(), 24), Placement.COUNT_RANGE, new CountRangeConfig(8, 23, 0, 37)));

           // End 
		   // Ores
		   // Ender Copper Ore
            Biomes.THE_END.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.ender_copper_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 128)));
            Biomes.END_BARRENS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.ender_copper_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 128)));
            Biomes.END_HIGHLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.ender_copper_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 128)));
            Biomes.END_MIDLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.ender_copper_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 128)));
            Biomes.SMALL_END_ISLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.ender_copper_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 128)));

            // Nether Purple Doritos Ore
            Biomes.THE_END.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.nether_purple_doritos_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
            Biomes.END_BARRENS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.nether_purple_doritos_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
            Biomes.END_HIGHLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.nether_purple_doritos_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
            Biomes.END_MIDLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.nether_purple_doritos_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
            Biomes.SMALL_END_ISLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.nether_purple_doritos_ore.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(20, 1, 0, 128)));
            
            // Not Ores
            // Ender Rock
            Biomes.THE_END.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.ender_rock.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 128)));
            Biomes.END_BARRENS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.ender_rock.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 128)));
            Biomes.END_HIGHLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.ender_rock.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 128)));
            Biomes.END_MIDLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.ender_rock.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 128)));
            Biomes.SMALL_END_ISLANDS.addFeature(Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.EMERALD_ORE, new ReplaceBlockConfig(Blocks.END_STONE.getDefaultState(), BlockList.ender_rock.getDefaultState()), Placement.COUNT_RANGE, new CountRangeConfig(25, 1, 0, 128)));
		}
	}
}
